# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       mer-kernel-checks

# >> macros
# << macros

Summary:    Mer kernel pre-build checks
Version:    0.0.2
Release:    1
Group:      Kernel/Linux Kernel
License:    GPLv2
URL:        https://github.com/lbt/mer-kernel-check/
Source0:    mer-kernel-checks-%{version}.tar.bz2
Source100:  mer-kernel-checks.yaml

%description
Scripts to check kernel CONFIG_ values used by Mer


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_bindir}/*
# >> files
# << files
